name: voila-starter-pack
channels:
- conda-forge
dependencies:
- bqplot=0.12
- gpxpy=1.3.5
- ipycanvas
- ipyleaflet=0.11
- ipympl
- ipyvuetify=1.1
- jupyterlab=1
- matplotlib
- nodejs
- notebook>=6
- numpy
- pandas
- python=3.7
- pip
- plotly=4.4
- ptvsd
- seaborn
- voila=0.1.20
- voila-gridstack
- voila-material=0.2
- voila-reveal=0.0.2
- voila-vuetify=0.2.2
- xeus-python=0.6
- pip:
  - srtm.py==0.3.4
  - jupyterlab-heroku
  - jupyterlab-git

